# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, default='ready', max_length=100)),
                ('alert_options', models.CharField(blank=True, default='alert', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='DataTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('data_value', models.CharField(blank=True, default='0', max_length=100)),
            ],
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='DateTimeTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('date_from', models.DateTimeField(default='0')),
                ('date_to', models.DateTimeField(default='0')),
            ],
            bases=('tasks.task',),
        ),
    ]
