# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 22:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(blank=True, default='0.0.0.0', max_length=100)),
                ('device_mac', models.CharField(blank=True, default='0', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='Elektron', max_length=100)),
                ('state', models.CharField(blank=True, default='Off', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
