# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
    ]
